inherit_from: .rubocop_todo.yml
# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - "vendor/**/*"

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
      - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
