version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          BUNDLE_JOBS: 3
          BUNDLE_RE TRY: 3
          BUNDLE_PATH: vendor/bundle
          PG_HOST: 127.0.0.1
          PG_DATABASE: postgres
          PG_PASSWORD: pass
          PG_USER: postgres
          SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
          RAILS_ENV: test
      - image: circleci/postgres:9.6-postgis-ram
        environment:
          POSTGRES_PASSWORD: pass
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    executor: ruby/default
    steps:
      - run:
          #日本語のファイルを読み込むため
          command: 'git config --global core.quotepath false'
      - checkout
      #bundleのアップデート
      - run:
          name: Install bundle
          command: |
            gem install bundle 
            bundle install --path vendor/bundle
            bundle install --jobs=4 --retry=3
      # bundlerのバージョンを表示
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle キャッシュをリストアする
      - restore_cache:
          keys:
            - task-bundle-v2-{{ checksum "Gemfile.lock" }}
            - task-bundle-v2-
      # bundle キャッシュを保存
      - save_cache:
          key: task-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      #rubocopの実行
      - run:
          name: Run rubocop
          command: bundle exec rubocop